version: "3.8"

services:
  app:
    build: ./
    ports:
      - "8000:5000"
    volumes:
      - type: bind
        source: ./bewise_test_task
        target: /app/bewise_test_task
    environment:
      DATABASE_URL: "postgresql://postgres:secret@db:5432/bewise_test_task"
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: postgres:14.2
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: bewise_test_task
      POSTGRES_PASSWORD: secret
    ports:
      - "45432:5432"

volumes:
  db-data:
